name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-roslyn@v16
      with:
        roslyn-version: 20190709.3
    - name: Build with roslyn
      run: csc -define:DEBUG -optimize -out:SirHurtAPI.dll SirHurtAPI/*.cs
